name: Deploy GitHub Pages

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          activate-environment: zensical-env
          environment-file: environment.yml

      - name: Install dependencies
        run: |
          conda info
          conda list
          conda run -n zensical-env python -m pip install -r requirements.txt

      - name: Build site
        run: |
          conda run -n zensical-env zensical build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          cname: jonaslindemann.github.io
          force_orphan: true
